/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2018-05-27 15:41:33 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/ethstream -t users -t transactions -s public
 *
 */

export namespace usersFields {
    export type id = string;
    export type twitch_id = number | null;
    export type streamlabs_token = string | null;
    export type eth_address = string | null;

}

export interface users {
    id: usersFields.id;
    twitch_id: usersFields.twitch_id;
    streamlabs_token: usersFields.streamlabs_token;
    eth_address: usersFields.eth_address;

}

export namespace transactionsFields {
    export type tx_hash = string;

}

export interface transactions {
    tx_hash: transactionsFields.tx_hash;

}
